//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikeMateWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string Id { get; set; }
        public double longitiude { get; set; }
        public double latitude { get; set; }
        public double currLongitiude { get; set; }
        public double currLattitude { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    }
}
